### PR TITLE
run.bat

### PR DESCRIPTION
**Pull request by Jayma1322**
i made run.bat files because without them this program sucks! /j
but on a serious note it makes it slightly tiny little bit more user friendly

### CODE REVIEW

**Comment by Jayma1322** [comment]
fuck wait i deleted package.json

**Comment by Jayma1322** [comment]
there

**Review by sudocode1 — CHANGES_REQUESTED** [review]
rename `run number 1` to `finishinstall` and rename `run number 2` to run

**Review by sudocode1 — CHANGES_REQUESTED** [review]
add this to secure server

**Review by sudocode1 — CHANGES_REQUESTED** [review]
add shell scripts too actually

**Pull request closed without merging**
